module BasicStrategy exposing (..)

import Html exposing (..)
import Html.Attributes exposing (..)


-- https://mbylstra.github.io/html-to-elm/
-- https://en.wikipedia.org/wiki/Blackjack#Blackjack_strategy


legend =
    dl []
        [ dd []
            [ span [ attribute "style" "background:red; color:black" ]
                [ b []
                    [ text "S" ]
                ]
            , text "= Stand"
            ]
        , dd []
            [ span [ attribute "style" "background:lime; color:black" ]
                [ b []
                    [ text "H" ]
                ]
            , text "= Hit"
            ]
        , dd []
            [ span [ attribute "style" "background:cyan; color:black" ]
                [ b []
                    [ text "Dh" ]
                ]
            , text "= Double (if not allowed, then hit)"
            ]
        , dd []
            [ span [ attribute "style" "background:cyan; color:black" ]
                [ b []
                    [ text "Ds" ]
                ]
            , text "= Double (if not allowed, then stand)"
            ]
        , dd []
            [ span [ attribute "style" "background:yellow; color:black" ]
                [ b []
                    [ text "SP" ]
                ]
            , text "= Split"
            ]
        , dd []
            [ span [ attribute "style" "background:white; color:black" ]
                [ b []
                    [ text "SU" ]
                ]
            , text "= Surrender (if not allowed, then hit)"
            ]
        ]


basicStrategy =
    table [ attribute "border" "1", class "wikitable", attribute "style" "text-align:center" ]
        [ tbody []
            [ tr []
                [ th [ attribute "rowspan" "2" ]
                    [ text "Player hand" ]
                , th [ attribute "colspan" "10" ]
                    [ text "Dealer's face-up card" ]
                ]
            , tr []
                [ td []
                    [ text "2" ]
                , td []
                    [ text "3" ]
                , td []
                    [ text "4" ]
                , td []
                    [ text "5" ]
                , td []
                    [ text "6" ]
                , td []
                    [ text "7" ]
                , td []
                    [ text "8" ]
                , td []
                    [ text "9" ]
                , td []
                    [ text "10" ]
                , td []
                    [ text "A" ]
                ]
            , tr []
                [ th [ attribute "colspan" "11" ]
                    [ text "Hard totals (excluding pairs)" ]
                ]
            , tr []
                [ th []
                    [ text "17–20" ]
                , td [ attribute "style" "background:red; color:black" ]
                    [ text "S" ]
                , td [ attribute "style" "background:red; color:black" ]
                    [ text "S" ]
                , td [ attribute "style" "background:red; color:black" ]
                    [ text "S" ]
                , td [ attribute "style" "background:red; color:black" ]
                    [ text "S" ]
                , td [ attribute "style" "background:red; color:black" ]
                    [ text "S" ]
                , td [ attribute "style" "background:red; color:black" ]
                    [ text "S" ]
                , td [ attribute "style" "background:red; color:black" ]
                    [ text "S" ]
                , td [ attribute "style" "background:red; color:black" ]
                    [ text "S" ]
                , td [ attribute "style" "background:red; color:black" ]
                    [ text "S" ]
                , td [ attribute "style" "background:red; color:black" ]
                    [ text "S" ]
                ]
            , tr []
                [ th []
                    [ text "16" ]
                , td [ attribute "style" "background:red; color:black" ]
                    [ text "S" ]
                , td [ attribute "style" "background:red; color:black" ]
                    [ text "S" ]
                , td [ attribute "style" "background:red; color:black" ]
                    [ text "S" ]
                , td [ attribute "style" "background:red; color:black" ]
                    [ text "S" ]
                , td [ attribute "style" "background:red; color:black" ]
                    [ text "S" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                , td [ attribute "style" "background:white; color:black" ]
                    [ text "SU" ]
                , td [ attribute "style" "background:white; color:black" ]
                    [ text "SU" ]
                , td [ attribute "style" "background:white; color:black" ]
                    [ text "SU" ]
                ]
            , tr []
                [ th []
                    [ text "15" ]
                , td [ attribute "style" "background:red; color:black" ]
                    [ text "S" ]
                , td [ attribute "style" "background:red; color:black" ]
                    [ text "S" ]
                , td [ attribute "style" "background:red; color:black" ]
                    [ text "S" ]
                , td [ attribute "style" "background:red; color:black" ]
                    [ text "S" ]
                , td [ attribute "style" "background:red; color:black" ]
                    [ text "S" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                , td [ attribute "style" "background:white; color:black" ]
                    [ text "SU" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                ]
            , tr []
                [ th []
                    [ text "13–14" ]
                , td [ attribute "style" "background:red; color:black" ]
                    [ text "S" ]
                , td [ attribute "style" "background:red; color:black" ]
                    [ text "S" ]
                , td [ attribute "style" "background:red; color:black" ]
                    [ text "S" ]
                , td [ attribute "style" "background:red; color:black" ]
                    [ text "S" ]
                , td [ attribute "style" "background:red; color:black" ]
                    [ text "S" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                ]
            , tr []
                [ th []
                    [ text "12" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                , td [ attribute "style" "background:red; color:black" ]
                    [ text "S" ]
                , td [ attribute "style" "background:red; color:black" ]
                    [ text "S" ]
                , td [ attribute "style" "background:red; color:black" ]
                    [ text "S" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                ]
            , tr []
                [ th []
                    [ text "11" ]
                , td [ attribute "style" "background:cyan; color:black" ]
                    [ text "Dh" ]
                , td [ attribute "style" "background:cyan; color:black" ]
                    [ text "Dh" ]
                , td [ attribute "style" "background:cyan; color:black" ]
                    [ text "Dh" ]
                , td [ attribute "style" "background:cyan; color:black" ]
                    [ text "Dh" ]
                , td [ attribute "style" "background:cyan; color:black" ]
                    [ text "Dh" ]
                , td [ attribute "style" "background:cyan; color:black" ]
                    [ text "Dh" ]
                , td [ attribute "style" "background:cyan; color:black" ]
                    [ text "Dh" ]
                , td [ attribute "style" "background:cyan; color:black" ]
                    [ text "Dh" ]
                , td [ attribute "style" "background:cyan; color:black" ]
                    [ text "Dh" ]
                , td [ attribute "style" "background:cyan; color:black" ]
                    [ text "Dh" ]
                ]
            , tr []
                [ th []
                    [ text "10" ]
                , td [ attribute "style" "background:cyan; color:black" ]
                    [ text "Dh" ]
                , td [ attribute "style" "background:cyan; color:black" ]
                    [ text "Dh" ]
                , td [ attribute "style" "background:cyan; color:black" ]
                    [ text "Dh" ]
                , td [ attribute "style" "background:cyan; color:black" ]
                    [ text "Dh" ]
                , td [ attribute "style" "background:cyan; color:black" ]
                    [ text "Dh" ]
                , td [ attribute "style" "background:cyan; color:black" ]
                    [ text "Dh" ]
                , td [ attribute "style" "background:cyan; color:black" ]
                    [ text "Dh" ]
                , td [ attribute "style" "background:cyan; color:black" ]
                    [ text "Dh" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                ]
            , tr []
                [ th []
                    [ text "9" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                , td [ attribute "style" "background:cyan; color:black" ]
                    [ text "Dh" ]
                , td [ attribute "style" "background:cyan; color:black" ]
                    [ text "Dh" ]
                , td [ attribute "style" "background:cyan; color:black" ]
                    [ text "Dh" ]
                , td [ attribute "style" "background:cyan; color:black" ]
                    [ text "Dh" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                ]
            , tr []
                [ th []
                    [ text "5–8" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                ]
            , tr []
                [ th [ attribute "colspan" "11" ]
                    [ text "Soft totals" ]
                ]
            , tr []
                [ td []
                    []
                , td []
                    [ text "2" ]
                , td []
                    [ text "3" ]
                , td []
                    [ text "4" ]
                , td []
                    [ text "5" ]
                , td []
                    [ text "6" ]
                , td []
                    [ text "7" ]
                , td []
                    [ text "8" ]
                , td []
                    [ text "9" ]
                , td []
                    [ text "10" ]
                , td []
                    [ text "A" ]
                ]
            , tr []
                [ th []
                    [ text "A,9" ]
                , td [ attribute "style" "background:red; color:black" ]
                    [ text "S" ]
                , td [ attribute "style" "background:red; color:black" ]
                    [ text "S" ]
                , td [ attribute "style" "background:red; color:black" ]
                    [ text "S" ]
                , td [ attribute "style" "background:red; color:black" ]
                    [ text "S" ]
                , td [ attribute "style" "background:red; color:black" ]
                    [ text "S" ]
                , td [ attribute "style" "background:red; color:black" ]
                    [ text "S" ]
                , td [ attribute "style" "background:red; color:black" ]
                    [ text "S" ]
                , td [ attribute "style" "background:red; color:black" ]
                    [ text "S" ]
                , td [ attribute "style" "background:red; color:black" ]
                    [ text "S" ]
                , td [ attribute "style" "background:red; color:black" ]
                    [ text "S" ]
                ]
            , tr []
                [ th []
                    [ text "A,8" ]
                , td [ attribute "style" "background:red; color:black" ]
                    [ text "S" ]
                , td [ attribute "style" "background:red; color:black" ]
                    [ text "S" ]
                , td [ attribute "style" "background:red; color:black" ]
                    [ text "S" ]
                , td [ attribute "style" "background:red; color:black" ]
                    [ text "S" ]
                , td [ attribute "style" "background:cyan; color:black" ]
                    [ text "Ds" ]
                , td [ attribute "style" "background:red; color:black" ]
                    [ text "S" ]
                , td [ attribute "style" "background:red; color:black" ]
                    [ text "S" ]
                , td [ attribute "style" "background:red; color:black" ]
                    [ text "S" ]
                , td [ attribute "style" "background:red; color:black" ]
                    [ text "S" ]
                , td [ attribute "style" "background:red; color:black" ]
                    [ text "S" ]
                ]
            , tr []
                [ th []
                    [ text "A,7" ]
                , td [ attribute "style" "background:cyan; color:black" ]
                    [ text "Ds" ]
                , td [ attribute "style" "background:cyan; color:black" ]
                    [ text "Ds" ]
                , td [ attribute "style" "background:cyan; color:black" ]
                    [ text "Ds" ]
                , td [ attribute "style" "background:cyan; color:black" ]
                    [ text "Ds" ]
                , td [ attribute "style" "background:cyan; color:black" ]
                    [ text "Ds" ]
                , td [ attribute "style" "background:red; color:black" ]
                    [ text "S" ]
                , td [ attribute "style" "background:red; color:black" ]
                    [ text "S" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                ]
            , tr []
                [ th []
                    [ text "A,6" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                , td [ attribute "style" "background:cyan; color:black" ]
                    [ text "Dh" ]
                , td [ attribute "style" "background:cyan; color:black" ]
                    [ text "Dh" ]
                , td [ attribute "style" "background:cyan; color:black" ]
                    [ text "Dh" ]
                , td [ attribute "style" "background:cyan; color:black" ]
                    [ text "Dh" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                ]
            , tr []
                [ th []
                    [ text "A,4–A,5" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                , td [ attribute "style" "background:cyan; color:black" ]
                    [ text "Dh" ]
                , td [ attribute "style" "background:cyan; color:black" ]
                    [ text "Dh" ]
                , td [ attribute "style" "background:cyan; color:black" ]
                    [ text "Dh" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                ]
            , tr []
                [ th []
                    [ text "A,2–A,3" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                , td [ attribute "style" "background:cyan; color:black" ]
                    [ text "Dh" ]
                , td [ attribute "style" "background:cyan; color:black" ]
                    [ text "Dh" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                ]
            , tr []
                [ th [ attribute "colspan" "11" ]
                    [ text "Pairs" ]
                ]
            , tr []
                [ td []
                    []
                , td []
                    [ text "2" ]
                , td []
                    [ text "3" ]
                , td []
                    [ text "4" ]
                , td []
                    [ text "5" ]
                , td []
                    [ text "6" ]
                , td []
                    [ text "7" ]
                , td []
                    [ text "8" ]
                , td []
                    [ text "9" ]
                , td []
                    [ text "10" ]
                , td []
                    [ text "A" ]
                ]
            , tr []
                [ th []
                    [ text "A,A" ]
                , td [ attribute "style" "background:yellow; color:black" ]
                    [ text "SP" ]
                , td [ attribute "style" "background:yellow; color:black" ]
                    [ text "SP" ]
                , td [ attribute "style" "background:yellow; color:black" ]
                    [ text "SP" ]
                , td [ attribute "style" "background:yellow; color:black" ]
                    [ text "SP" ]
                , td [ attribute "style" "background:yellow; color:black" ]
                    [ text "SP" ]
                , td [ attribute "style" "background:yellow; color:black" ]
                    [ text "SP" ]
                , td [ attribute "style" "background:yellow; color:black" ]
                    [ text "SP" ]
                , td [ attribute "style" "background:yellow; color:black" ]
                    [ text "SP" ]
                , td [ attribute "style" "background:yellow; color:black" ]
                    [ text "SP" ]
                , td [ attribute "style" "background:yellow; color:black" ]
                    [ text "SP" ]
                ]
            , tr []
                [ th []
                    [ text "10,10" ]
                , td [ attribute "style" "background:red; color:black" ]
                    [ text "S" ]
                , td [ attribute "style" "background:red; color:black" ]
                    [ text "S" ]
                , td [ attribute "style" "background:red; color:black" ]
                    [ text "S" ]
                , td [ attribute "style" "background:red; color:black" ]
                    [ text "S" ]
                , td [ attribute "style" "background:red; color:black" ]
                    [ text "S" ]
                , td [ attribute "style" "background:red; color:black" ]
                    [ text "S" ]
                , td [ attribute "style" "background:red; color:black" ]
                    [ text "S" ]
                , td [ attribute "style" "background:red; color:black" ]
                    [ text "S" ]
                , td [ attribute "style" "background:red; color:black" ]
                    [ text "S" ]
                , td [ attribute "style" "background:red; color:black" ]
                    [ text "S" ]
                ]
            , tr []
                [ th []
                    [ text "9,9" ]
                , td [ attribute "style" "background:yellow; color:black" ]
                    [ text "SP" ]
                , td [ attribute "style" "background:yellow; color:black" ]
                    [ text "SP" ]
                , td [ attribute "style" "background:yellow; color:black" ]
                    [ text "SP" ]
                , td [ attribute "style" "background:yellow; color:black" ]
                    [ text "SP" ]
                , td [ attribute "style" "background:yellow; color:black" ]
                    [ text "SP" ]
                , td [ attribute "style" "background:red; color:black" ]
                    [ text "S" ]
                , td [ attribute "style" "background:yellow; color:black" ]
                    [ text "SP" ]
                , td [ attribute "style" "background:yellow; color:black" ]
                    [ text "SP" ]
                , td [ attribute "style" "background:red; color:black" ]
                    [ text "S" ]
                , td [ attribute "style" "background:red; color:black" ]
                    [ text "S" ]
                ]
            , tr []
                [ th []
                    [ text "8,8" ]
                , td [ attribute "style" "background:yellow; color:black" ]
                    [ text "SP" ]
                , td [ attribute "style" "background:yellow; color:black" ]
                    [ text "SP" ]
                , td [ attribute "style" "background:yellow; color:black" ]
                    [ text "SP" ]
                , td [ attribute "style" "background:yellow; color:black" ]
                    [ text "SP" ]
                , td [ attribute "style" "background:yellow; color:black" ]
                    [ text "SP" ]
                , td [ attribute "style" "background:yellow; color:black" ]
                    [ text "SP" ]
                , td [ attribute "style" "background:yellow; color:black" ]
                    [ text "SP" ]
                , td [ attribute "style" "background:yellow; color:black" ]
                    [ text "SP" ]
                , td [ attribute "style" "background:yellow; color:black" ]
                    [ text "SP" ]
                , td [ attribute "style" "background:yellow; color:black" ]
                    [ text "SP" ]
                ]
            , tr []
                [ th []
                    [ text "7,7" ]
                , td [ attribute "style" "background:yellow; color:black" ]
                    [ text "SP" ]
                , td [ attribute "style" "background:yellow; color:black" ]
                    [ text "SP" ]
                , td [ attribute "style" "background:yellow; color:black" ]
                    [ text "SP" ]
                , td [ attribute "style" "background:yellow; color:black" ]
                    [ text "SP" ]
                , td [ attribute "style" "background:yellow; color:black" ]
                    [ text "SP" ]
                , td [ attribute "style" "background:yellow; color:black" ]
                    [ text "SP" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                ]
            , tr []
                [ th []
                    [ text "6,6" ]
                , td [ attribute "style" "background:yellow; color:black" ]
                    [ text "SP" ]
                , td [ attribute "style" "background:yellow; color:black" ]
                    [ text "SP" ]
                , td [ attribute "style" "background:yellow; color:black" ]
                    [ text "SP" ]
                , td [ attribute "style" "background:yellow; color:black" ]
                    [ text "SP" ]
                , td [ attribute "style" "background:yellow; color:black" ]
                    [ text "SP" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                ]
            , tr []
                [ th []
                    [ text "5,5" ]
                , td [ attribute "style" "background:cyan; color:black" ]
                    [ text "Dh" ]
                , td [ attribute "style" "background:cyan; color:black" ]
                    [ text "Dh" ]
                , td [ attribute "style" "background:cyan; color:black" ]
                    [ text "Dh" ]
                , td [ attribute "style" "background:cyan; color:black" ]
                    [ text "Dh" ]
                , td [ attribute "style" "background:cyan; color:black" ]
                    [ text "Dh" ]
                , td [ attribute "style" "background:cyan; color:black" ]
                    [ text "Dh" ]
                , td [ attribute "style" "background:cyan; color:black" ]
                    [ text "Dh" ]
                , td [ attribute "style" "background:cyan; color:black" ]
                    [ text "Dh" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                ]
            , tr []
                [ th []
                    [ text "4,4" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                , td [ attribute "style" "background:yellow; color:black" ]
                    [ text "SP" ]
                , td [ attribute "style" "background:yellow; color:black" ]
                    [ text "SP" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                ]
            , tr []
                [ th []
                    [ text "2,2–3,3" ]
                , td [ attribute "style" "background:yellow; color:black" ]
                    [ text "SP" ]
                , td [ attribute "style" "background:yellow; color:black" ]
                    [ text "SP" ]
                , td [ attribute "style" "background:yellow; color:black" ]
                    [ text "SP" ]
                , td [ attribute "style" "background:yellow; color:black" ]
                    [ text "SP" ]
                , td [ attribute "style" "background:yellow; color:black" ]
                    [ text "SP" ]
                , td [ attribute "style" "background:yellow; color:black" ]
                    [ text "SP" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                , td [ attribute "style" "background:lime; color:black" ]
                    [ text "H" ]
                ]
            ]
        ]
