module BasicStrategy exposing (..)

import Html exposing (..)
import Html.Attributes exposing (..)
import Score


-- https://mbylstra.github.io/html-to-elm/
-- https://en.wikipedia.org/wiki/Blackjack#Blackjack_strategy


legend : Html msg
legend =
    dl []
        [ dd []
            [ span [ attribute "style" "background:red; color:black" ]
                [ b []
                    [ text "S" ]
                ]
            , text "= Stand"
            ]
        , dd []
            [ span [ attribute "style" "background:lime; color:black" ]
                [ b []
                    [ text "H" ]
                ]
            , text "= Hit"
            ]
        , dd []
            [ span [ attribute "style" "background:cyan; color:black" ]
                [ b []
                    [ text "Dh" ]
                ]
            , text "= Double (if not allowed, then hit)"
            ]
        , dd []
            [ span [ attribute "style" "background:cyan; color:black" ]
                [ b []
                    [ text "Ds" ]
                ]
            , text "= Double (if not allowed, then stand)"
            ]
        , dd []
            [ span [ attribute "style" "background:yellow; color:black" ]
                [ b []
                    [ text "SP" ]
                ]
            , text "= Split"
            ]
        , dd []
            [ span [ attribute "style" "background:white; color:black" ]
                [ b []
                    [ text "SU" ]
                ]
            , text "= Surrender (if not allowed, then hit)"
            ]
        ]


hasAce : Score.Score -> Bool
hasAce playerScore =
    playerScore.hard /= playerScore.soft


playerScoreAttributes : Int -> List Int -> Attribute a
playerScoreAttributes score range =
    case List.member score range of
        True ->
            attribute "style" "background:purple; color:black"

        False ->
            attribute "style" ""


dealerScoreAttribute : Int -> Int -> Attribute a
dealerScoreAttribute score value =
    case score == value of
        True ->
            attribute "style" "background:purple; color:black"

        False ->
            attribute "style" ""


dealerSoftScoreAttribute : Bool -> Int -> Int -> Attribute a
dealerSoftScoreAttribute hasAce score value =
    case hasAce of
        True ->
            case score == value of
                True ->
                    attribute "style" "background:purple; color:black"

                False ->
                    attribute "style" ""

        False ->
            attribute "style" ""


playerSoftScoreAttribute : Bool -> Int -> List Int -> Attribute msg
playerSoftScoreAttribute hasAce score range =
    case hasAce of
        True ->
            playerScoreAttributes score range

        False ->
            attribute "style" ""


basicStrategy :
    { a
        | dealerHand : List String
        , playerHand : List String
        , playerScore : Score.Score
    }
    -> Html msg
basicStrategy model =
    let
        playerScore =
            model.playerScore

        playerHasAce =
            hasAce model.playerScore

        playerScoreWithoutAce =
            Score.scoreMinusAce model.playerHand

        dealerScore =
            Score.makeScoreFromHand <| Maybe.withDefault [] <| List.tail model.dealerHand

        playerHandIsPair =
            Score.handIsPair model.playerHand
    in
        table [ attribute "border" "1", class "wikitable", attribute "style" "text-align:center" ]
            [ tbody []
                [ tr []
                    [ th [ attribute "rowspan" "2" ]
                        [ text "Player hand" ]
                    , th [ attribute "colspan" "10" ]
                        [ text "Dealer's face-up card" ]
                    ]
                , tr []
                    [ td [ dealerScoreAttribute dealerScore.hard 2 ]
                        [ text "2" ]
                    , td [ dealerScoreAttribute dealerScore.hard 3 ]
                        [ text "3" ]
                    , td [ dealerScoreAttribute dealerScore.hard 4 ]
                        [ text "4" ]
                    , td [ dealerScoreAttribute dealerScore.hard 5 ]
                        [ text "5" ]
                    , td [ dealerScoreAttribute dealerScore.hard 6 ]
                        [ text "6" ]
                    , td [ dealerScoreAttribute dealerScore.hard 7 ]
                        [ text "7" ]
                    , td [ dealerScoreAttribute dealerScore.hard 8 ]
                        [ text "8" ]
                    , td [ dealerScoreAttribute dealerScore.hard 9 ]
                        [ text "9" ]
                    , td [ dealerScoreAttribute dealerScore.hard 10 ]
                        [ text "10" ]
                    , td [ dealerScoreAttribute dealerScore.hard 11 ]
                        [ text "A" ]
                    ]
                , tr []
                    [ th [ attribute "colspan" "11" ]
                        [ text "Hard totals (excluding pairs)" ]
                    ]
                , tr []
                    [ th [ playerScoreAttributes playerScore.hard (List.range 17 20) ]
                        [ text "17–20" ]
                    , td [ attribute "style" "background:red; color:black" ]
                        [ text "S" ]
                    , td [ attribute "style" "background:red; color:black" ]
                        [ text "S" ]
                    , td [ attribute "style" "background:red; color:black" ]
                        [ text "S" ]
                    , td [ attribute "style" "background:red; color:black" ]
                        [ text "S" ]
                    , td [ attribute "style" "background:red; color:black" ]
                        [ text "S" ]
                    , td [ attribute "style" "background:red; color:black" ]
                        [ text "S" ]
                    , td [ attribute "style" "background:red; color:black" ]
                        [ text "S" ]
                    , td [ attribute "style" "background:red; color:black" ]
                        [ text "S" ]
                    , td [ attribute "style" "background:red; color:black" ]
                        [ text "S" ]
                    , td [ attribute "style" "background:red; color:black" ]
                        [ text "S" ]
                    ]
                , tr []
                    [ th [ playerScoreAttributes playerScore.hard (List.range 16 16) ]
                        [ text "16" ]
                    , td [ attribute "style" "background:red; color:black" ]
                        [ text "S" ]
                    , td [ attribute "style" "background:red; color:black" ]
                        [ text "S" ]
                    , td [ attribute "style" "background:red; color:black" ]
                        [ text "S" ]
                    , td [ attribute "style" "background:red; color:black" ]
                        [ text "S" ]
                    , td [ attribute "style" "background:red; color:black" ]
                        [ text "S" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    , td [ attribute "style" "background:white; color:black" ]
                        [ text "SU" ]
                    , td [ attribute "style" "background:white; color:black" ]
                        [ text "SU" ]
                    , td [ attribute "style" "background:white; color:black" ]
                        [ text "SU" ]
                    ]
                , tr []
                    [ th [ playerScoreAttributes playerScore.hard (List.range 15 15) ]
                        [ text "15" ]
                    , td [ attribute "style" "background:red; color:black" ]
                        [ text "S" ]
                    , td [ attribute "style" "background:red; color:black" ]
                        [ text "S" ]
                    , td [ attribute "style" "background:red; color:black" ]
                        [ text "S" ]
                    , td [ attribute "style" "background:red; color:black" ]
                        [ text "S" ]
                    , td [ attribute "style" "background:red; color:black" ]
                        [ text "S" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    , td [ attribute "style" "background:white; color:black" ]
                        [ text "SU" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    ]
                , tr []
                    [ th [ playerScoreAttributes playerScore.hard (List.range 13 14) ]
                        [ text "13–14" ]
                    , td [ attribute "style" "background:red; color:black" ]
                        [ text "S" ]
                    , td [ attribute "style" "background:red; color:black" ]
                        [ text "S" ]
                    , td [ attribute "style" "background:red; color:black" ]
                        [ text "S" ]
                    , td [ attribute "style" "background:red; color:black" ]
                        [ text "S" ]
                    , td [ attribute "style" "background:red; color:black" ]
                        [ text "S" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    ]
                , tr []
                    [ th [ playerScoreAttributes playerScore.hard (List.range 12 12) ]
                        [ text "12" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    , td [ attribute "style" "background:red; color:black" ]
                        [ text "S" ]
                    , td [ attribute "style" "background:red; color:black" ]
                        [ text "S" ]
                    , td [ attribute "style" "background:red; color:black" ]
                        [ text "S" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    ]
                , tr []
                    [ th [ playerScoreAttributes playerScore.hard (List.range 11 11) ]
                        [ text "11" ]
                    , td [ attribute "style" "background:cyan; color:black" ]
                        [ text "Dh" ]
                    , td [ attribute "style" "background:cyan; color:black" ]
                        [ text "Dh" ]
                    , td [ attribute "style" "background:cyan; color:black" ]
                        [ text "Dh" ]
                    , td [ attribute "style" "background:cyan; color:black" ]
                        [ text "Dh" ]
                    , td [ attribute "style" "background:cyan; color:black" ]
                        [ text "Dh" ]
                    , td [ attribute "style" "background:cyan; color:black" ]
                        [ text "Dh" ]
                    , td [ attribute "style" "background:cyan; color:black" ]
                        [ text "Dh" ]
                    , td [ attribute "style" "background:cyan; color:black" ]
                        [ text "Dh" ]
                    , td [ attribute "style" "background:cyan; color:black" ]
                        [ text "Dh" ]
                    , td [ attribute "style" "background:cyan; color:black" ]
                        [ text "Dh" ]
                    ]
                , tr []
                    [ th [ playerScoreAttributes playerScore.hard (List.range 10 10) ]
                        [ text "10" ]
                    , td [ attribute "style" "background:cyan; color:black" ]
                        [ text "Dh" ]
                    , td [ attribute "style" "background:cyan; color:black" ]
                        [ text "Dh" ]
                    , td [ attribute "style" "background:cyan; color:black" ]
                        [ text "Dh" ]
                    , td [ attribute "style" "background:cyan; color:black" ]
                        [ text "Dh" ]
                    , td [ attribute "style" "background:cyan; color:black" ]
                        [ text "Dh" ]
                    , td [ attribute "style" "background:cyan; color:black" ]
                        [ text "Dh" ]
                    , td [ attribute "style" "background:cyan; color:black" ]
                        [ text "Dh" ]
                    , td [ attribute "style" "background:cyan; color:black" ]
                        [ text "Dh" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    ]
                , tr []
                    [ th [ playerScoreAttributes playerScore.hard (List.range 9 9) ]
                        [ text "9" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    , td [ attribute "style" "background:cyan; color:black" ]
                        [ text "Dh" ]
                    , td [ attribute "style" "background:cyan; color:black" ]
                        [ text "Dh" ]
                    , td [ attribute "style" "background:cyan; color:black" ]
                        [ text "Dh" ]
                    , td [ attribute "style" "background:cyan; color:black" ]
                        [ text "Dh" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    ]
                , tr []
                    [ th [ playerScoreAttributes playerScore.hard (List.range 5 8) ]
                        [ text "5–8" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    ]
                , tr []
                    [ th [ attribute "colspan" "11" ]
                        [ text "Soft totals" ]
                    ]
                , tr []
                    [ td []
                        []
                    , td [ dealerSoftScoreAttribute playerHasAce dealerScore.soft 2 ]
                        [ text "2" ]
                    , td [ dealerSoftScoreAttribute playerHasAce dealerScore.soft 3 ]
                        [ text "3" ]
                    , td [ dealerSoftScoreAttribute playerHasAce dealerScore.soft 4 ]
                        [ text "4" ]
                    , td [ dealerSoftScoreAttribute playerHasAce dealerScore.soft 5 ]
                        [ text "5" ]
                    , td [ dealerSoftScoreAttribute playerHasAce dealerScore.soft 6 ]
                        [ text "6" ]
                    , td [ dealerSoftScoreAttribute playerHasAce dealerScore.soft 7 ]
                        [ text "7" ]
                    , td [ dealerSoftScoreAttribute playerHasAce dealerScore.soft 8 ]
                        [ text "8" ]
                    , td [ dealerSoftScoreAttribute playerHasAce dealerScore.soft 9 ]
                        [ text "9" ]
                    , td [ dealerSoftScoreAttribute playerHasAce dealerScore.soft 10 ]
                        [ text "10" ]
                    , td [ dealerSoftScoreAttribute playerHasAce dealerScore.soft 1 ]
                        [ text "A" ]
                    ]
                , tr []
                    [ th [ playerSoftScoreAttribute playerHasAce playerScoreWithoutAce <| List.range 9 9 ]
                        [ text "A,9" ]
                    , td [ attribute "style" "background:red; color:black" ]
                        [ text "S" ]
                    , td [ attribute "style" "background:red; color:black" ]
                        [ text "S" ]
                    , td [ attribute "style" "background:red; color:black" ]
                        [ text "S" ]
                    , td [ attribute "style" "background:red; color:black" ]
                        [ text "S" ]
                    , td [ attribute "style" "background:red; color:black" ]
                        [ text "S" ]
                    , td [ attribute "style" "background:red; color:black" ]
                        [ text "S" ]
                    , td [ attribute "style" "background:red; color:black" ]
                        [ text "S" ]
                    , td [ attribute "style" "background:red; color:black" ]
                        [ text "S" ]
                    , td [ attribute "style" "background:red; color:black" ]
                        [ text "S" ]
                    , td [ attribute "style" "background:red; color:black" ]
                        [ text "S" ]
                    ]
                , tr []
                    [ th [ playerSoftScoreAttribute playerHasAce playerScoreWithoutAce <| List.range 8 8 ]
                        [ text "A,8" ]
                    , td [ attribute "style" "background:red; color:black" ]
                        [ text "S" ]
                    , td [ attribute "style" "background:red; color:black" ]
                        [ text "S" ]
                    , td [ attribute "style" "background:red; color:black" ]
                        [ text "S" ]
                    , td [ attribute "style" "background:red; color:black" ]
                        [ text "S" ]
                    , td [ attribute "style" "background:cyan; color:black" ]
                        [ text "Ds" ]
                    , td [ attribute "style" "background:red; color:black" ]
                        [ text "S" ]
                    , td [ attribute "style" "background:red; color:black" ]
                        [ text "S" ]
                    , td [ attribute "style" "background:red; color:black" ]
                        [ text "S" ]
                    , td [ attribute "style" "background:red; color:black" ]
                        [ text "S" ]
                    , td [ attribute "style" "background:red; color:black" ]
                        [ text "S" ]
                    ]
                , tr []
                    [ th [ playerSoftScoreAttribute playerHasAce playerScoreWithoutAce <| List.range 7 7 ]
                        [ text "A,7" ]
                    , td [ attribute "style" "background:cyan; color:black" ]
                        [ text "Ds" ]
                    , td [ attribute "style" "background:cyan; color:black" ]
                        [ text "Ds" ]
                    , td [ attribute "style" "background:cyan; color:black" ]
                        [ text "Ds" ]
                    , td [ attribute "style" "background:cyan; color:black" ]
                        [ text "Ds" ]
                    , td [ attribute "style" "background:cyan; color:black" ]
                        [ text "Ds" ]
                    , td [ attribute "style" "background:red; color:black" ]
                        [ text "S" ]
                    , td [ attribute "style" "background:red; color:black" ]
                        [ text "S" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    ]
                , tr []
                    [ th [ playerSoftScoreAttribute playerHasAce playerScoreWithoutAce <| List.range 6 6 ]
                        [ text "A,6" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    , td [ attribute "style" "background:cyan; color:black" ]
                        [ text "Dh" ]
                    , td [ attribute "style" "background:cyan; color:black" ]
                        [ text "Dh" ]
                    , td [ attribute "style" "background:cyan; color:black" ]
                        [ text "Dh" ]
                    , td [ attribute "style" "background:cyan; color:black" ]
                        [ text "Dh" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    ]
                , tr []
                    [ th [ playerSoftScoreAttribute playerHasAce playerScoreWithoutAce <| List.range 4 5 ]
                        [ text "A,4–A,5" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    , td [ attribute "style" "background:cyan; color:black" ]
                        [ text "Dh" ]
                    , td [ attribute "style" "background:cyan; color:black" ]
                        [ text "Dh" ]
                    , td [ attribute "style" "background:cyan; color:black" ]
                        [ text "Dh" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    ]
                , tr []
                    [ th [ playerSoftScoreAttribute playerHasAce playerScoreWithoutAce <| List.range 2 3 ]
                        [ text "A,2–A,3" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    , td [ attribute "style" "background:cyan; color:black" ]
                        [ text "Dh" ]
                    , td [ attribute "style" "background:cyan; color:black" ]
                        [ text "Dh" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    ]
                , tr []
                    [ th [ attribute "colspan" "11" ]
                        [ text "Pairs" ]
                    ]
                , tr []
                    [ td []
                        []
                    , td [ dealerSoftScoreAttribute playerHandIsPair dealerScore.soft 2 ]
                        [ text "2" ]
                    , td [ dealerSoftScoreAttribute playerHandIsPair dealerScore.soft 3 ]
                        [ text "3" ]
                    , td [ dealerSoftScoreAttribute playerHandIsPair dealerScore.soft 4 ]
                        [ text "4" ]
                    , td [ dealerSoftScoreAttribute playerHandIsPair dealerScore.soft 5 ]
                        [ text "5" ]
                    , td [ dealerSoftScoreAttribute playerHandIsPair dealerScore.soft 6 ]
                        [ text "6" ]
                    , td [ dealerSoftScoreAttribute playerHandIsPair dealerScore.soft 7 ]
                        [ text "7" ]
                    , td [ dealerSoftScoreAttribute playerHandIsPair dealerScore.soft 8 ]
                        [ text "8" ]
                    , td [ dealerSoftScoreAttribute playerHandIsPair dealerScore.soft 9 ]
                        [ text "9" ]
                    , td [ dealerSoftScoreAttribute playerHandIsPair dealerScore.soft 10 ]
                        [ text "10" ]
                    , td [ dealerSoftScoreAttribute playerHandIsPair dealerScore.soft 11 ]
                        [ text "A" ]
                    ]
                , tr []
                    [ th [ playerSoftScoreAttribute playerHandIsPair playerScore.hard [ 22 ] ]
                        [ text "A,A" ]
                    , td [ attribute "style" "background:yellow; color:black" ]
                        [ text "SP" ]
                    , td [ attribute "style" "background:yellow; color:black" ]
                        [ text "SP" ]
                    , td [ attribute "style" "background:yellow; color:black" ]
                        [ text "SP" ]
                    , td [ attribute "style" "background:yellow; color:black" ]
                        [ text "SP" ]
                    , td [ attribute "style" "background:yellow; color:black" ]
                        [ text "SP" ]
                    , td [ attribute "style" "background:yellow; color:black" ]
                        [ text "SP" ]
                    , td [ attribute "style" "background:yellow; color:black" ]
                        [ text "SP" ]
                    , td [ attribute "style" "background:yellow; color:black" ]
                        [ text "SP" ]
                    , td [ attribute "style" "background:yellow; color:black" ]
                        [ text "SP" ]
                    , td [ attribute "style" "background:yellow; color:black" ]
                        [ text "SP" ]
                    ]
                , tr []
                    [ th [ playerSoftScoreAttribute playerHandIsPair playerScore.soft [ 20 ] ]
                        [ text "10,10" ]
                    , td [ attribute "style" "background:red; color:black" ]
                        [ text "S" ]
                    , td [ attribute "style" "background:red; color:black" ]
                        [ text "S" ]
                    , td [ attribute "style" "background:red; color:black" ]
                        [ text "S" ]
                    , td [ attribute "style" "background:red; color:black" ]
                        [ text "S" ]
                    , td [ attribute "style" "background:red; color:black" ]
                        [ text "S" ]
                    , td [ attribute "style" "background:red; color:black" ]
                        [ text "S" ]
                    , td [ attribute "style" "background:red; color:black" ]
                        [ text "S" ]
                    , td [ attribute "style" "background:red; color:black" ]
                        [ text "S" ]
                    , td [ attribute "style" "background:red; color:black" ]
                        [ text "S" ]
                    , td [ attribute "style" "background:red; color:black" ]
                        [ text "S" ]
                    ]
                , tr []
                    [ th [ playerSoftScoreAttribute playerHandIsPair playerScore.soft [ 18 ] ]
                        [ text "9,9" ]
                    , td [ attribute "style" "background:yellow; color:black" ]
                        [ text "SP" ]
                    , td [ attribute "style" "background:yellow; color:black" ]
                        [ text "SP" ]
                    , td [ attribute "style" "background:yellow; color:black" ]
                        [ text "SP" ]
                    , td [ attribute "style" "background:yellow; color:black" ]
                        [ text "SP" ]
                    , td [ attribute "style" "background:yellow; color:black" ]
                        [ text "SP" ]
                    , td [ attribute "style" "background:red; color:black" ]
                        [ text "S" ]
                    , td [ attribute "style" "background:yellow; color:black" ]
                        [ text "SP" ]
                    , td [ attribute "style" "background:yellow; color:black" ]
                        [ text "SP" ]
                    , td [ attribute "style" "background:red; color:black" ]
                        [ text "S" ]
                    , td [ attribute "style" "background:red; color:black" ]
                        [ text "S" ]
                    ]
                , tr []
                    [ th [ playerSoftScoreAttribute playerHandIsPair playerScore.soft [ 16 ] ]
                        [ text "8,8" ]
                    , td [ attribute "style" "background:yellow; color:black" ]
                        [ text "SP" ]
                    , td [ attribute "style" "background:yellow; color:black" ]
                        [ text "SP" ]
                    , td [ attribute "style" "background:yellow; color:black" ]
                        [ text "SP" ]
                    , td [ attribute "style" "background:yellow; color:black" ]
                        [ text "SP" ]
                    , td [ attribute "style" "background:yellow; color:black" ]
                        [ text "SP" ]
                    , td [ attribute "style" "background:yellow; color:black" ]
                        [ text "SP" ]
                    , td [ attribute "style" "background:yellow; color:black" ]
                        [ text "SP" ]
                    , td [ attribute "style" "background:yellow; color:black" ]
                        [ text "SP" ]
                    , td [ attribute "style" "background:yellow; color:black" ]
                        [ text "SP" ]
                    , td [ attribute "style" "background:yellow; color:black" ]
                        [ text "SP" ]
                    ]
                , tr []
                    [ th [ playerSoftScoreAttribute playerHandIsPair playerScore.soft [ 14 ] ]
                        [ text "7,7" ]
                    , td [ attribute "style" "background:yellow; color:black" ]
                        [ text "SP" ]
                    , td [ attribute "style" "background:yellow; color:black" ]
                        [ text "SP" ]
                    , td [ attribute "style" "background:yellow; color:black" ]
                        [ text "SP" ]
                    , td [ attribute "style" "background:yellow; color:black" ]
                        [ text "SP" ]
                    , td [ attribute "style" "background:yellow; color:black" ]
                        [ text "SP" ]
                    , td [ attribute "style" "background:yellow; color:black" ]
                        [ text "SP" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    ]
                , tr []
                    [ th [ playerSoftScoreAttribute playerHandIsPair playerScore.soft [ 12 ] ]
                        [ text "6,6" ]
                    , td [ attribute "style" "background:yellow; color:black" ]
                        [ text "SP" ]
                    , td [ attribute "style" "background:yellow; color:black" ]
                        [ text "SP" ]
                    , td [ attribute "style" "background:yellow; color:black" ]
                        [ text "SP" ]
                    , td [ attribute "style" "background:yellow; color:black" ]
                        [ text "SP" ]
                    , td [ attribute "style" "background:yellow; color:black" ]
                        [ text "SP" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    ]
                , tr []
                    [ th [ playerSoftScoreAttribute playerHandIsPair playerScore.soft [ 10 ] ]
                        [ text "5,5" ]
                    , td [ attribute "style" "background:cyan; color:black" ]
                        [ text "Dh" ]
                    , td [ attribute "style" "background:cyan; color:black" ]
                        [ text "Dh" ]
                    , td [ attribute "style" "background:cyan; color:black" ]
                        [ text "Dh" ]
                    , td [ attribute "style" "background:cyan; color:black" ]
                        [ text "Dh" ]
                    , td [ attribute "style" "background:cyan; color:black" ]
                        [ text "Dh" ]
                    , td [ attribute "style" "background:cyan; color:black" ]
                        [ text "Dh" ]
                    , td [ attribute "style" "background:cyan; color:black" ]
                        [ text "Dh" ]
                    , td [ attribute "style" "background:cyan; color:black" ]
                        [ text "Dh" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    ]
                , tr []
                    [ th [ playerSoftScoreAttribute playerHandIsPair playerScore.soft [ 8 ] ]
                        [ text "4,4" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    , td [ attribute "style" "background:yellow; color:black" ]
                        [ text "SP" ]
                    , td [ attribute "style" "background:yellow; color:black" ]
                        [ text "SP" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    ]
                , tr []
                    [ th [ playerSoftScoreAttribute playerHandIsPair playerScore.soft [ 4, 6 ] ]
                        [ text "2,2–3,3" ]
                    , td [ attribute "style" "background:yellow; color:black" ]
                        [ text "SP" ]
                    , td [ attribute "style" "background:yellow; color:black" ]
                        [ text "SP" ]
                    , td [ attribute "style" "background:yellow; color:black" ]
                        [ text "SP" ]
                    , td [ attribute "style" "background:yellow; color:black" ]
                        [ text "SP" ]
                    , td [ attribute "style" "background:yellow; color:black" ]
                        [ text "SP" ]
                    , td [ attribute "style" "background:yellow; color:black" ]
                        [ text "SP" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    , td [ attribute "style" "background:lime; color:black" ]
                        [ text "H" ]
                    ]
                ]
            ]
